"""The core domain objects, mirroring the frozen ThrottleKit ``Decision`` / ``Forecast``.

Field names are snake_case (Python protobuf keeps the proto's snake_case fields), which is why the
JSON golden vectors — generated by the Node core with camelCase keys — are mapped explicitly where they
are consumed, never relied on by attribute name.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class Decision:
    """The immutable result of one rate-limit check — the five frozen fields of the core ``Decision``."""

    allowed: bool
    """Whether the request is permitted."""
    limit: int
    """Effective ceiling: burst capacity (GCRA / token bucket) or window quota."""
    remaining: int
    """Whole units remaining before the next rejection. Never negative."""
    reset_at: int
    """Epoch-ms at which the limiter is fully replenished."""
    retry_after_ms: int
    """Milliseconds to wait before retrying. ``0`` when :attr:`allowed`."""


@dataclass(frozen=True)
class Forecast:
    """A non-consuming projection of a key's near-future capacity."""

    spendable_now: int
    """Whole units of the given cost admissible right now before the next denial."""
    next_replenish_at: int
    """Epoch-ms when capacity next increases by at least one unit."""
    full_at: int
    """Epoch-ms when the limiter is fully replenished to its ceiling from the current state."""
